export const auditActions = {
  loginSucceeded: "LOGIN_SUCCEEDED",
  loginFailed: "LOGIN_FAILED",
  logout: "LOGOUT",
  refreshTokenReuseDetected: "REFRESH_TOKEN_REUSE_DETECTED",
  accountLocked: "ACCOUNT_LOCKED",
  accountUnlocked: "ACCOUNT_UNLOCKED",
  userCreated: "USER_CREATED",
  userUpdated: "USER_UPDATED",
  userDisplayNameUpdated: "USER_DISPLAY_NAME_UPDATED",
  userPasswordChanged: "USER_PASSWORD_CHANGED",
  userActivated: "USER_ACTIVATED",
  userDeactivated: "USER_DEACTIVATED",
  systemAdminGranted: "SYSTEM_ADMIN_GRANTED",
  systemAdminRemoved: "SYSTEM_ADMIN_REMOVED",
  registerCreated: "REGISTER_CREATED",
  registerSettingsUpdated: "REGISTER_SETTINGS_UPDATED",
  registerAdminAdded: "REGISTER_ADMIN_ADDED",
  registerAdminRemoved: "REGISTER_ADMIN_REMOVED",
  registerViewerAdded: "REGISTER_VIEWER_ADDED",
  registerViewerRemoved: "REGISTER_VIEWER_REMOVED",
  riskCreated: "RISK_CREATED",
  riskUpdated: "RISK_UPDATED",
  riskDeleted: "RISK_DELETED",
  riskReviewed: "RISK_REVIEWED",
  nextReviewDateUpdated: "NEXT_REVIEW_DATE_UPDATED",
  riskExportGenerated: "RISK_EXPORT_GENERATED",
  customFieldCreated: "CUSTOM_FIELD_CREATED",
  customFieldUpdated: "CUSTOM_FIELD_UPDATED",
  customFieldActivated: "CUSTOM_FIELD_ACTIVATED",
  customFieldDeactivated: "CUSTOM_FIELD_DEACTIVATED",
  customFieldOptionCreated: "CUSTOM_FIELD_OPTION_CREATED",
  customFieldOptionUpdated: "CUSTOM_FIELD_OPTION_UPDATED",
  customFieldOptionDeactivated: "CUSTOM_FIELD_OPTION_DEACTIVATED",
  likelihoodValueCreated: "LIKELIHOOD_VALUE_CREATED",
  likelihoodValueUpdated: "LIKELIHOOD_VALUE_UPDATED",
  likelihoodValueDeactivated: "LIKELIHOOD_VALUE_DEACTIVATED",
  impactValueCreated: "IMPACT_VALUE_CREATED",
  impactValueUpdated: "IMPACT_VALUE_UPDATED",
  impactValueDeactivated: "IMPACT_VALUE_DEACTIVATED",
  riskLevelCreated: "RISK_LEVEL_CREATED",
  riskLevelUpdated: "RISK_LEVEL_UPDATED",
  riskLevelDeactivated: "RISK_LEVEL_DEACTIVATED",
  riskMatrixUpdated: "RISK_MATRIX_UPDATED"
} as const;

export type AuditAction = (typeof auditActions)[keyof typeof auditActions];
